### ISSUE TITLE
Sketch Text Doesn't Resize

### ISSUE THREAD

**Issue by jcamato** [tylergaw/icon-stamper#9]
I used your plugin, but my sketch text that was inside my icon group stayed the same font size and wasn't resized like the other layers. Aside from that, it worked great!
![example](https://cloud.githubusercontent.com/assets/10441545/7174110/23269de2-e3b7-11e4-93db-24c5fb7ffc5e.png)

**Comment by tylergaw** [comment]
@jcamato Sorry for not responding on this when you reported it. A fix was merged in #10 and I just created a new release with it https://github.com/tylergaw/icon-stamper/releases/tag/v1.1.1
